---
valid_motors: # Motors
    - m1 
    - m2
#     - m3
    - m4
#     rot
limits:
    m1: [0, 300]
    m2: [0, 190]
    m3: [0, 100]
    m4: [0, 100]
tolerance: # Maximum position error
    m1: .01
    m2: .008
    m3: .005
    m4: .005
    rot: .0031
fiber_limits: # XY limits with fiber extended
    m1: [115, 185]
    m2: [85, 155]
mask_limits: # XY limits with mask extended
    m1: [95, 115]
    m2: [175, 190]
