---
valid_motors: # Motors
    - m1 
    - m2
#     - m3
    - m4
#     rot
motor_limits:
    m1: [0, 300]
    m2: [0, 190]
    m3: [0, 100]
    m4: [0, 100]
tolerance: # Maximum position error
    m1: .01
    m2: .008
    m3: .005
    m4: .005
    rot: .0031
fiber_center: # XY limits with fiber extended
    m1: 150
    m2: 120
mask_center: # XY limits with mask extended
    m1: 105
    m2: 184
safe_radius: # safe radius around center of k-mirror hole
    fiber: 35
    mask: 35
