---
pinhole_mask:
    m1: 105 # X stage
    m2: 190 # Y stage
    m3: 100 # Z stage (pinhole mask)
    m4: 0 # Z stage (fiber bundle)
#     m5: 0 # Rotation stage
fiber_bundle:
    m1: 150
    m2: 120
    m3: 0
    m4: 100
#     m5: 0
kpf_mirror:
    m1: 105
    m2: 60
    m3: 0
    m4: 0
#     m5: 0
telescope_sim:
    m1: 260
    m2: 0
    m3: 0
    m4: 0
#     m5: 0
telescope:
    m1: 0
    m2: 0
    m3: 0
    m4: 0
#     m5: 0